import Link from "next/link";
import {portfolioData as d} from "@/data/portfolioData";
const A=()=> <span aria-hidden>↗</span>;
const portrait=["https:","//avatars.githubusercontent.com/u/70061426?v=4"].join("");
const fooracles=["https:","//www.google.com/s2/favicons?domain=fooracles.com&sz=128"].join("");
const cert=["https:","//drive.google.com/file/d/1RHxzQh9YDPj2O2M5FyJzfv8gwwg5I96m/view?usp=sharing"].join("");
export default function PortfolioHome(){return <div className="editorial-home">
<section className="editorial-hero"><div className="editorial-frame editorial-hero-grid"><div className="editorial-hero-copy"><p className="editorial-eyebrow">{d.hero.eyebrow}</p><h1 className="editorial-hero-title"><span>{d.hero.heading}</span><em>{d.hero.emphasis}</em></h1><p className="editorial-hero-description">{d.hero.description}</p><p className="editorial-hero-context">{d.hero.context}</p><div className="editorial-link-row"><a className="editorial-link editorial-link-strong" href="#work">View selected work ↓</a><Link className="editorial-link" href="/resume">Resume <A/></Link></div></div><figure className="editorial-portrait-block"><div className="editorial-portrait-frame"><img src={portrait} alt="Amar Jyoti" className="editorial-portrait"/></div><figcaption>Amar Jyoti · Delhi NCR</figcaption></figure></div><div className="editorial-frame editorial-fact-strip">{d.hero.facts.map(x=><div className="editorial-fact" key={x.label}><span>{x.label}</span><strong>{x.value}</strong></div>)}</div></section>
<section id="work" className="editorial-case-study"><div className="editorial-frame"><header className="editorial-case-header"><div className="editorial-case-number">01</div><div><p className="editorial-section-label">{d.flagship.label}</p><h2>{d.flagship.title}</h2><p className="editorial-case-headline">{d.flagship.headline}</p></div></header><div className="editorial-case-grid"><div className="editorial-case-story"><article className="editorial-story-block"><span>Problem</span><p>{d.flagship.problem}</p></article><article className="editorial-story-block"><span>What I built</span><p>{d.flagship.built}</p></article><div className="editorial-flow"><span className="editorial-flow-label">Workflow</span><ol>{d.flagship.flow.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></li>)}</ol></div><div className="editorial-decisions"><p className="editorial-section-label">Product decisions</p>{d.flagship.decisions.map((x,i)=><article className="editorial-decision-row" key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.body}</p></article>)}</div></div><aside className="editorial-evidence-column"><div className="editorial-evidence-heading"><p className="editorial-section-label">{d.flagship.validation.heading}</p><h3>{d.flagship.validation.fixture}</h3></div><div className="editorial-metric-list">{d.flagship.validation.metrics.map(x=><div className="editorial-metric-row" key={x.label}><strong>{x.value}</strong><span>{x.label}</span></div>)}</div><div className="editorial-stack-block"><span>Built with</span><p className="editorial-stack-line">{d.flagship.stack.join(" · ")}</p></div><div className="editorial-live-block"><a className="editorial-link editorial-link-light" href={d.flagship.liveUrl}>Open live product <A/></a></div></aside></div></div></section>
<section className="editorial-section editorial-frame"><header className="editorial-section-head"><p className="editorial-section-label">Selected Work</p><h2>A few more things I’ve built or studied.</h2></header><div className="editorial-work-list">{d.selectedWork.map(x=><article className="editorial-work-row" key={x.number}><div className="editorial-work-number">{x.number}</div><div className="editorial-work-main"><h3>{x.title}</h3><p>{x.summary}</p></div><div className="editorial-work-proof"><span>Why it matters</span><p>{x.proof}</p><p className="editorial-stack-line">{x.stack.join(" · ")}</p><a className="editorial-text-link" href={x.link.href}>Open <A/></a></div></article>)}</div></section>
<section id="about" className="editorial-about-band"><div className="editorial-frame editorial-about-grid"><div className="editorial-about-intro"><p className="editorial-section-label">About</p><h2>{d.about.heading}</h2></div><div className="editorial-about-copy">{d.about.paragraphs.map(x=><p key={x}>{x}</p>)}</div></div></section>
<section id="experience" className="editorial-section editorial-frame"><header className="editorial-section-head editorial-section-head-compact"><p className="editorial-section-label">Experience</p><h2>Research, product thinking and technical communication.</h2></header><div className="editorial-experience-list">{d.experience.map(x=><article className="editorial-experience-row" key={x.organization}><span className="editorial-period">{x.period}</span><div><h3>{x.role}</h3><p className="editorial-organization">{x.organization}</p>{x.organization==="Fooracles"&&<a href={cert} target="_blank" rel="noreferrer" className="editorial-text-link"><img src={fooracles} alt="Fooracles logo" className="experience-logo"/> Certificate <A/></a>}</div><p>{x.description}</p></article>)}</div></section>
<section className="editorial-section editorial-frame"><header className="editorial-section-head editorial-section-head-compact"><p className="editorial-section-label">Capabilities</p><h2>Tools that support the work.</h2></header><div className="editorial-capability-list">{d.capabilities.map(x=><div className="editorial-capability-row" key={x.title}><h3>{x.title}</h3><p>{x.items}</p></div>)}</div></section>
<section className="editorial-section editorial-frame"><header className="editorial-section-head editorial-section-head-compact"><p className="editorial-section-label">Education and Signals</p><h2>Technical foundation, business context.</h2></header><div className="editorial-education-list">{d.education.map(x=><article className="editorial-education-row" key={x.institution}><span>{x.period}</span><div><h3>{x.institution}</h3><p>{x.degree}</p></div><strong>{x.result}</strong></article>)}</div><div className="editorial-highlight-line">{d.highlights.map(x=><span key={x}>{x}</span>)}</div></section>
<footer id="contact" className="editorial-footer"><div className="editorial-frame editorial-footer-grid"><div><p className="editorial-section-label editorial-section-label-light">Contact</p><h2>{d.contact.heading}</h2></div><div className="editorial-footer-copy"><p>{d.contact.description}</p><div className="editorial-footer-links"><Link href="/resume">Resume <A/></Link></div></div></div></footer>
</div>}